storyNine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('story_9.urls')),
    path('admin/', admin.site.urls),
]

story_9/urls.py
from django.urls import path
from . import views

app_name = 'story_9'

urlpatterns = [
	path('', views.story9, name= 'story9'),
	path('login/', views.login_view, name = 'login'),
	path('logout/', views.logout_view, name = 'logout'),

    
    # dilanjutkan ...
]

story_9/models.py
from django.db import models

# Create your models here.

story_9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


# Create your views here.

def story9(request):
	# form = AuthenticationForm(data=request.POST)
	return render(request, 'login.html')

# dari netninja wkwk
def login_view(request):
	error = "Terdapat kesalahan dalam memasukkan username ataupun password"
	# user = request.user
	# if user.is_authenticated:
	# 	return redirect('story_9:story9')
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			#login the user
			user = form.get_user()
			login(request, user)
			return redirect('story_9:story9')
	else:
		form = AuthenticationForm()
	return render(request, 'story9.html', {'form':form, 'error':error})		


def logout_view(request):
		logout(request)
		return redirect('story_9:login')

story_9/templates/login.html
{% load static %}

</div>
    {% if user.is_authenticated %}
    <h1>Haloo {{user}} !!!</h1> 
    <a href="{% url 'story_9:logout' %}">
        <div class='logout'>
            Log out
        </div> 
    </a>
    {% else %}
    <h1>Please login</h1>
    <a href="{% url 'story_9:login' %}">
        <div class='login'>
            Log in
        </div>
    </a>
    {% endif %}

story_9/templates/story9.html
{% load static %}

</div>
    {% if form.errors %}
    {{error}}
    {% endif %}
    <form method="POST" action="{% url 'story_9:login' %}">
        {% csrf_token %}
        <label>Username</label>
        <br>
        {{ form.username }}
        <br>
        <label>Password</label>
        <br>
        {{ form.password }}
        <br>
        <input type="submit" value="Log in" class="button">
    </form>


    <p> username : admin </p>
    <p> password : adminadmin </p>